import java.util.Random;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }


    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        float f1= (float) 3.14;
        System.out.println(f1);
        long i1=2000000007204545454L;
        System.out.println(i1);
        Random r;
        r = new Random();
        System.out.println(r.nextLong());

        int count=0;

        for(int i=1; i<20; i=i+1){
            int i2=r.nextInt();
            if (i2%2==1) {
                System.out.print("1");
            }
            else {
                count=count+1;
                System.out.print("0");
                if (count==10)
                    break;

            }
        }

/*        int i2=r.nextInt();
        if (i2%2==1) {
            System.out.println("1");
        }
        else {
            System.out.println("0");
        }*/
    }
}

class App2 {
    int kvadrat(int valuekvadrat) {
    int resultat = valuekvadrat*valuekvadrat;
        return resultat;
    }
}