/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void test1() {
        App2 classUnderTest = new App2();
        assertEquals(4, classUnderTest.kvadrat(2));
        assertEquals(81, classUnderTest.kvadrat(9));
    }
}


